[0.008s] Invoking command in '/home/dky/Projects/dky_robot/build/robot_interfaces': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/opt/ros/humble /usr/bin/cmake --build /home/dky/Projects/dky_robot/build/robot_interfaces -- -j20 -l20
[0.032s] -- Found ament_cmake: 1.3.8 (/opt/ros/humble/share/ament_cmake/cmake)
[0.142s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.144s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.145s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.168s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.185s] -- Found geometry_msgs: 4.2.3 (/opt/ros/humble/share/geometry_msgs/cmake)
[0.394s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.394s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[0.394s]   robot_interfaces --arguments-file
[0.394s]   /home/dky/Projects/dky_robot/build/robot_interfaces/rosidl_adapter__arguments__robot_interfaces.json
[0.394s]   --output-dir
[0.394s]   /home/dky/Projects/dky_robot/build/robot_interfaces/rosidl_adapter/robot_interfaces
[0.394s]   --output-file
[0.394s]   /home/dky/Projects/dky_robot/build/robot_interfaces/rosidl_adapter/robot_interfaces.idls)
[0.395s]   returned error code 1:
[0.395s] 
[0.395s]   Error processing 'tf2::Quaternion end_effector_quat;' of
[0.395s]   'robot_interfaces/QtRecv': ''tf2::Quaternion' is an invalid message name.
[0.395s]   It should have the pattern '^[A-Z][A-Za-z0-9]*$''
[0.395s] 
[0.395s]   Traceback (most recent call last):
[0.395s] 
[0.395s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.395s]       return _run_code(code, main_globals, None,
[0.395s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.395s]       exec(code, run_globals)
[0.395s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.396s]       sys.exit(main())
[0.396s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.396s]       abs_idl_file = convert_to_idl(
[0.396s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.396s]       return convert_msg_to_idl(
[0.396s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.396s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.396s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
[0.396s]       Type(type_string, context_package_name=pkg_name),
[0.396s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 277, in __init__
[0.396s]       super(Type, self).__init__(
[0.396s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.397s]       raise InvalidResourceName(
[0.397s] 
[0.397s]   rosidl_adapter.parser.InvalidResourceName: 'tf2::Quaternion' is an invalid
[0.397s]   message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.397s] 
[0.397s] Call Stack (most recent call first):
[0.397s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.397s]   CMakeLists.txt:18 (rosidl_generate_interfaces)
[0.397s] 
[0.397s] [0m
[0.397s] -- Configuring incomplete, errors occurred!
[0.398s] See also "/home/dky/Projects/dky_robot/build/robot_interfaces/CMakeFiles/CMakeOutput.log".
[0.398s] gmake: *** [Makefile:963: cmake_check_build_system] Error 1
[0.400s] Invoked command in '/home/dky/Projects/dky_robot/build/robot_interfaces' returned '2': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/opt/ros/humble /usr/bin/cmake --build /home/dky/Projects/dky_robot/build/robot_interfaces -- -j20 -l20
